name: "banana"

trainer:
  output_path: "outputs/custom"
  max_steps: 30000
  val_interval: 10000
  training: True
  enable_gui: True

  spatial_lr_scale: True
  model:
    name: GaussianFlow
    lambda_ssim: 0.2
    point_cloud:
      point_cloud_type: "GaussianFlowPointCloud"  
      trainable: true
      unwarp_prefix: "point_cloud"
      max_sh_degree: 3
      pos_traj_dim: 3
      rot_traj_dim: 3
      feat_traj_dim: 3
      rescale_value: 0.7
      offset_value: 0.1
      initializer:
        # init_type: 'colmap'
        num_points: 10000
        radius: 0.5
        init_type: 'random'
        feat_dim: 3
    camera_model:
      name: TimeCameraModel
      enable_training: False
    renderer:
      name: "GaussianFlowRender"
      render_depth: False
      update_sh_iter: 1000
      max_sh_degree: ${trainer.model.point_cloud.max_sh_degree}
  
  controller:
    name: GFDensificationController
    normalize_grad: False
    control_module: "point_cloud"
    densify_start_iter: 500
    densify_stop_iter: 15000
    prune_interval: 100
    duplicate_interval: 100
    opacity_reset_interval: 3000
    densify_grad_threshold: 0.0002
    min_opacity: 0.001
    optimizer_name: "optimizer_1"

  gui:
    name: GaussianFlowGUI
    viewer_port: 9012

  optimizer:
    optimizer_1:
      type: BaseOptimizer
      name: Adam
      args:
        eps: 1e-15
      extra_cfg:
        backward: False
      params:
        point_cloud.position:
          lr: 0.000016
        point_cloud.pos_params:
          lr: 0.00005
        point_cloud.features:
          lr: 0.0025
        point_cloud.features_rest:
          lr: 0.000125 # features/20
        point_cloud.feat_params:
          lr: 0.0025
        point_cloud.scaling:
          lr: 0.005
        point_cloud.rotation:
          lr: 0.001
        point_cloud.rot_params:
          lr: 0.005
        point_cloud.opacity:
          lr: 0.05
        point_cloud.time_center:
          lr: 0.001
  scheduler:
    name: "ExponLRScheduler"
    params:
      point_cloud.position:
        init:  0.000016
        final: 0.00000016
        max_steps: 30000
      point_cloud.pos_params:
        init:  0.00005
        final: 0.0000005
        max_steps: 30000
  
  datapipeline:
    data_set: "CustomDataset"
    shuffle: True
    batch_size: 1
    num_workers: 0
    dataset:
      # data_path: "/NASdata/clz/data/vrig-peel-banana"
      cached_observed_data: True
      scale: 0.5
      white_bg: False
      observed_data_dirs_dict: {"image": "images"}

  writer:
    writer_type: "TensorboardWriter"
  
  hooks:
    LogHook:
      name: LogHook
    CheckPointHook:
      name: CheckPointHook
  
  exporter:
    exporter_1:
      type: MetricExporter